server:
  port: 5001
  servlet:
    application-display-name: client
    context-path: /cag/client

spring:
  application:
    name: ms-client
  jackson:
    time-zone: America/Sao_Paulo

logging:
  level:
    org:
      springframework:
        web: info
---
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: cag