server:
  port: 5004
  servlet:
    application-display-name: lineup
    context-path: /futebola/lineup

spring:
  application:
    name: lineup
  jackson:
    time-zone: America/Sao_Paulo

logging:
  level:
    org:
      springframework:
        web: info
---
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: futebola
---
app:
  lineup:
    total-players: 11
    total-reserves: 3
  errors:
    response:
      number-starting-players: "Número de jogadores titulares: %s vs número informado: %s"
      number-reserve-players: "Número de jogadores reservas: %s vs número informado: %s"
      formation: "Divergência entre formação %s vs jogadores por posição %s"
      round: "Janela da rodada com fechamento: %s e reabertura: %s vs horário: %s"