server:
  port: 5004
  servlet:
    application-display-name: lineup
    context-path: /futebola/lineup

spring:
  application:
    name: lineup
  jackson:
    time-zone: America/Sao_Paulo

logging:
  level:
    org:
      springframework:
        web: info
---
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: futebola
---
app:
  errors:
    response:
      quantity-players: "Número de jogadores titulares inválido: %s"
      quantity-reserves: "Número de jogadores reservas inválido: %s"
      formation: "Divergência entre formação %s vs jogadores por posição %s"