server:
  port: 5004
  servlet:
    application-display-name: lineup
    context-path: /futebola/lineup

spring:
  application:
    name: lineup
  jackson:
    time-zone: America/Sao_Paulo

logging:
  level:
    org:
      springframework:
        web: info
---
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: futebola
---
app:
  lineup:
    total-players: 11
    total-reserves: 3
  errors:
    messages:
      number-starting-players: "Número de jogadores titulares: %s vs número informado: %s"
      number-reserve-players: "Número de jogadores reservas: %s vs número informado: %s"
      formation: "Divergência entre formação %s vs jogadores por posição %s"
      round: "Janela da rodada com fechamento: %s e reabertura: %s vs horário: %s"
      not-found-gamer: "Jogador com uuid %s ainda não fez cadastro na plataforma"
      points-gamer: "Pontuação distribuída %s maior do que pontuação do apostador %s"
  client:
    endpoints:
      game-uuid-user: http://localhost:5005/futebola/game/gamers/uuid-user?uuid-user={uuidUser}
  rules:
    validation-formation: false
    validation-points-gamer-players: false
    validation-reserve-players: false
    validation-round: false
    validation-starting-players: true