server:
  port: 5003
  servlet:
    application-display-name: sofascore
    context-path: /futebola/sofascore

spring:
  application:
    name: sofascore
  jackson:
    time-zone: America/Sao_Paulo

logging:
  level:
    org:
      springframework:
        web: info
---
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: futebola

rapidapi:
  sofascore:
    credentials:
      x-rapidapi-host: sofascore.p.rapidapi.com
      x-rapidapi-key: 67f551b823msh34866d68c74885cp1f1224jsnd7e6dabf5245
    endpoints:
      get-standings: https://sofascore.p.rapidapi.com/tournaments/get-standings